---
all:  # 顶级节点，表示所有主机的集合
  children:
    maas_postgres:  # MAAS PostgreSQL 数据库服务器组
      hosts:
        server1:
          ansible_host: 100.110.100.1
          ansible_user: admin1
          ansible_password: 123456
          ansible_become_pass: 123456
    maas_region_controller:  # MAAS 区域控制器组
      hosts:
        server1:
          ansible_host: 100.110.100.1
          ansible_user: admin1
          ansible_password: 123456
          ansible_become_pass: 123456
    maas_rack_controller:  # MAAS 机架控制器组
      hosts:
        server1:
          ansible_host: 100.110.100.1
          ansible_user: admin1
          ansible_password: 123456
          ansible_become_pass: 123456
