---
- hosts: all
  tasks:
    - name: "确保必需的变量已定义"
      ansible.builtin.assert:
        quiet: true
        fail_msg: "必需的变量未定义"
        that:
          - k3s_version is defined
          - awx_operator_version is defined
          - tower_hostname is defined
          - awx_admin_user is defined
          - awx_admin_password is defined

    - name: "运行 k3s 安装任务"
      ansible.builtin.include_tasks:
        file: ring0-k3s/setup_k3s.yml
